---
- name: Test Ansible Runner
  hosts: all
  remote_user: ec2-user


  tasks:
  - name: Install Apache Webserver
    yum:
      name: httpd
      state: latest

  - name: Make sure Apache is running and starts at boot
    systemd:
      name: httpd
      state: started
      enabled: yes

